# Generated by Django 6.0.6 on 2026-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('cooking', '料理'), ('prep', '下準備'), ('cleanup', '片付け'), ('other', 'その他')], default='cooking', max_length=10, verbose_name='作業タイプ')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='工程名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='所要時間(分)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程一覧',
            },
        ),
    ]
