# Generated by Django 6.0.6 on 2026-07-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='献立名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='調理予定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '献立',
                'verbose_name_plural': '献立一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='作業名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順番')),
                ('start_offset', models.PositiveIntegerField(default=0, verbose_name='開始オフセット（分）')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='所要時間（分）')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='献立')),
            ],
            options={
                'verbose_name': '作業',
                'verbose_name_plural': '作業一覧',
                'ordering': ['order'],
            },
        ),
    ]
