# Generated by Django 6.0.6 on 2026-07-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='関連レシピ'),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.PositiveIntegerField(default=0, verbose_name='開始時間（分）'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='所要時間（分）'),
        ),
    ]
