# Generated by Django 6.0.6 on 2026-07-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_created_at_step_duration'),
        ('tasks', '0002_task_recipe_task_start_alter_task_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start',
        ),
        migrations.RemoveField(
            model_name='task',
            name='work_type',
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('cooking', '料理'), ('prep', '下準備'), ('cleanup', '片付け'), ('other', 'その他')], default='cooking', max_length=10, verbose_name='作業タイプ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('start', models.PositiveIntegerField(default=0, verbose_name='開始時間（分）')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='所要時間（分）')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='関連レシピ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.task')),
            ],
        ),
    ]
