# Generated by Django 6.0.6 on 2026-08-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_membership_project_alter_task_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.project', verbose_name='project'),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='道具')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具一覧',
            },
        ),
    ]
