# Generated by Django 6.0.6 on 2026-10-06 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='グループ名')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leder_cooking_groups', to=settings.AUTH_USER_MODEL, verbose_name='リーダー')),
                ('members', models.ManyToManyField(blank=True, related_name='cooking_groups', to=settings.AUTH_USER_MODEL, verbose_name='メンバー')),
            ],
        ),
    ]
