# Generated by Django 6.0.6 on 2026-10-06 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cookinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookinggroup',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_cooking_groups', to=settings.AUTH_USER_MODEL, verbose_name='リーダー'),
        ),
    ]
