# Generated by Django 6.0.6 on 2026-10-08 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, verbose_name='料理名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='使用量')),
                ('name', models.CharField(max_length=30, verbose_name='材料名')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='単位')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='順番')),
                ('leave', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('prep', '下ごしらえ'), ('mix', '混ぜる・こねる'), ('heat', '加熱する'), ('rest', '冷ます・休ませる'), ('plate', '盛り付ける'), ('cleanup', '洗い物・片付け'), ('other', 'その他')], default='other')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='所要時間（分）')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='作業名')),
                ('description', models.TextField(blank=True, verbose_name='工程内容')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
