# Generated by Django 6.0.6 on 2026-09-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='category',
            field=models.CharField(choices=[('prep', '下ごしらえ'), ('mix', '混ぜる・こねる'), ('heat', '加熱する'), ('rest', '冷ます・休ませる'), ('plate', '盛り付ける'), ('cleanup', '洗い物・片付け'), ('other', 'その他')], default='other'),
        ),
    ]
