# Generated by Django 6.0.6 on 2026-09-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_step_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='leave',
            field=models.BooleanField(default=False),
        ),
    ]
