# Generated by Django 6.0.6 on 2026-09-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_step_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='作業名'),
        ),
    ]
