# Generated by Django 6.0.6 on 2026-10-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, verbose_name='工程内容'),
        ),
    ]
