# Generated by Django 6.0.6 on 2026-09-06 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='献立名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='調理予定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '献立',
                'verbose_name_plural': '献立一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='schedules.project', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='作業名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='順番')),
                ('start_offset', models.PositiveIntegerField(default=0, verbose_name='オフセット（分）')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='所要時間（分）')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='schedules.membership', verbose_name='担当者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedules.project', verbose_name='作業')),
            ],
            options={
                'verbose_name': '作業',
                'verbose_name_plural': '作業一覧',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='道具')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具一覧',
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('project', 'user'), name='unique_project_user'),
        ),
    ]
