# Generated by Django 6.0.6 on 2026-09-12 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='from_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_offset',
            field=models.IntegerField(default=0, verbose_name='オフセット（分）'),
        ),
    ]
