# Generated by Django 6.0.6 on 2026-09-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '作業', 'verbose_name_plural': '作業一覧'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
